-- Rollback for 20261006090058_prd139c_2_revoke_dead_tables.sql
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.weimi_product_alias TO authenticated;
GRANT SELECT, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.weimi_product_alias TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.product_mapping_backup_20260715 TO authenticated;
GRANT SELECT, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.product_mapping_backup_20260715 TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.product_mapping_backup_20260718 TO authenticated;
GRANT SELECT, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.product_mapping_backup_20260718 TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.product_mapping_backup_20260718b TO authenticated;
GRANT SELECT, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.product_mapping_backup_20260718b TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.product_mapping_backup_20260718c TO authenticated;
GRANT SELECT, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.product_mapping_backup_20260718c TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public._prd129_baseline_20260922 TO authenticated;
GRANT SELECT, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public._prd129_baseline_20260922 TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.warehouse_audit_baseline TO authenticated;
GRANT SELECT, REFERENCES, TRIGGER, MAINTAIN
  ON TABLE public.warehouse_audit_baseline TO anon;
