-- PRD-139b Item 2A rollback: re-grant EXECUTE to anon on exactly the 321 functions
-- snapshotted in supabase/rollbacks/prd139b_2a_anon_list.txt before the revoke.
-- Does not touch the authenticated/service_role grants the migration also added.
-- Does not revert the ALTER DEFAULT PRIVILEGES change (left in place deliberately:
-- a rollback of this item should not silently re-open every future function too).

GRANT EXECUTE ON FUNCTION public._assert_gate_zero(p_plan_date date) TO anon;
GRANT EXECUTE ON FUNCTION public._assert_refill_plan_writable(p_plan_date date, p_machine_ids uuid[]) TO anon;
GRANT EXECUTE ON FUNCTION public._coexistence_blocks(p_machine_id uuid, p_cand_boonz uuid) TO anon;
GRANT EXECUTE ON FUNCTION public._travel_scope_blocks(p_machine_id uuid, p_cand_boonz uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.abandon_intent(p_intent_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.ack_finding(p_finding_id uuid, p_note text) TO anon;
GRANT EXECUTE ON FUNCTION public.acknowledge_intent_threat(p_threat_id uuid, p_note text) TO anon;
GRANT EXECUTE ON FUNCTION public.acknowledge_m2m_transfer(p_transfer_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.acknowledge_wm_alert(p_source text, p_dedup_key text, p_note text, p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.acquire_refill_plan_lock(p_plan_date date, p_context text) TO anon;
GRANT EXECUTE ON FUNCTION public.add_dispatch_row(p_machine_id uuid, p_shelf_code text, p_boonz_product_id uuid, p_quantity numeric, p_action text, p_dispatch_date date, p_source_kind text, p_source_warehouse_id uuid, p_source_machine_id uuid, p_edit_role text, p_reason text, p_conductor_session text, p_partner_dispatch_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.add_intra_machine_move(p_machine_id uuid, p_from_shelf_code text, p_to_shelf_code text, p_boonz_product_id uuid, p_quantity numeric, p_dispatch_date date, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.add_m2m_transfer(p_source_machine_id uuid, p_source_shelf_code text, p_dest_machine_id uuid, p_dest_shelf_code text, p_boonz_product_id uuid, p_quantity numeric, p_dispatch_date date, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.add_machine_to_plan(p_plan_date date, p_machine_id uuid, p_confirm boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.add_new_machine(p_pod_number text, p_official_name text, p_location_type text, p_pod_location text, p_status text, p_include_in_refill boolean, p_installation_date date, p_notes text) TO anon;
GRANT EXECUTE ON FUNCTION public.add_pod_refill_row(p_plan_date date, p_machine_id uuid, p_shelf_id uuid, p_pod_product_id uuid, p_action text, p_qty integer, p_reason text, p_conductor_session text) TO anon;
GRANT EXECUTE ON FUNCTION public.add_purchase_order_lines(p_po_id text, p_lines jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.add_sanity_increment(p_run_id uuid, p_dispatch_date date, p_machine_name text, p_shelf_code text, p_pod_product_name text, p_increment_qty integer, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.adjust_pod_inventory(p_machine_name text, p_snapshot_date date, p_lines jsonb, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.agenda_items_tracker_column_guard() TO anon;
GRANT EXECUTE ON FUNCTION public.align_pod_lots_to_weimi(p_machine_id uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.apply_expiry_check(p_pod_inventory_id uuid, p_outcome text, p_qty numeric, p_new_expiry date, p_actor uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.apply_inventory_correction(p_wh_inventory_id uuid, p_boonz_product_id uuid, p_warehouse_id uuid, p_expiration_date date, p_new_warehouse_stock numeric, p_reason text, p_corrected_by uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.apply_mix_weight_recommendation(p_machine_id uuid, p_shelf_id uuid, p_boonz_product_id uuid, p_delta numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.apply_recommendation_intent(p_intent_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.apply_warehouse_audit(p_audit_date date, p_actor uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.approve_pod_inventory_add(p_edit_id uuid, p_approver_id uuid, p_decision_note text, p_expiry_override_accepted boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.approve_pod_inventory_edit(p_edit_id uuid, p_approver_id uuid, p_decision_note text, p_expiry_override_accepted boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.approve_refill_plan(p_plan_date date, p_machine_names text[], p_waive jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.approve_return(p_wh_inventory_id uuid, p_approver_id uuid, p_note text, p_corrected_expiry date, p_corrected_qty numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.approve_strategic_machine_tags(p_intent_id uuid, p_machine_names text[]) TO anon;
GRANT EXECUTE ON FUNCTION public.approve_stuck_remove(p_dispatch_id uuid, p_qty_received numeric, p_batch_breakdown jsonb, p_approved_by uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.assert_weimi_slot_match(p_plan_date date, p_mode text, p_machine_name text) TO anon;
GRANT EXECUTE ON FUNCTION public.assign_finding(p_finding_id uuid, p_owner_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.attempt_inventory_correction(p_session_id uuid, p_wh_inventory_id uuid, p_new_warehouse_stock numeric, p_reason text, p_client_correlation_id uuid, p_attempted_by uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.attempt_reactivate_row(p_session_id uuid, p_wh_inventory_id uuid, p_new_warehouse_stock numeric, p_reason text, p_client_correlation_id uuid, p_attempted_by uuid, p_source_doc text, p_new_expiration_date date, p_new_wh_location text) TO anon;
GRANT EXECUTE ON FUNCTION public.attempt_status_change(p_session_id uuid, p_wh_inventory_id uuid, p_new_status text, p_reason text, p_client_correlation_id uuid, p_attempted_by uuid, p_new_warehouse_stock numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.audit_m2m_dispatch_changes() TO anon;
GRANT EXECUTE ON FUNCTION public.audit_machine_duplicates() TO anon;
GRANT EXECUTE ON FUNCTION public.auto_audit_warehouse_inventory() TO anon;
GRANT EXECUTE ON FUNCTION public.auto_audit_warehouse_inventory_insert() TO anon;
GRANT EXECUTE ON FUNCTION public.auto_decrement_pod_inventory() TO anon;
GRANT EXECUTE ON FUNCTION public.auto_expire_pod_add_proposals() TO anon;
GRANT EXECUTE ON FUNCTION public.auto_expire_pod_inventory_edits() TO anon;
GRANT EXECUTE ON FUNCTION public.auto_generate_draft(p_plan_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.auto_sanity_check(p_dispatch_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.backfill_archive_pod_inventory_row(p_pod_inventory_id uuid, p_reason text, p_edit_id_link uuid, p_caller_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.backfill_dispatch_boonz_product_ids(p_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.backfill_mix_weight_from_split_pct(p_confirm boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.bind_fefo_reserved(p_dispatch_id uuid, p_ttl_minutes integer) TO anon;
GRANT EXECUTE ON FUNCTION public.block_direct_pod_inventory_insert() TO anon;
GRANT EXECUTE ON FUNCTION public.block_orphan_internal_transfer() TO anon;
GRANT EXECUTE ON FUNCTION public.boonz_product_block_reason(p_boonz_product_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.bug006_007_nightly_check() TO anon;
GRANT EXECUTE ON FUNCTION public.build_draft_for_confirmed(p_plan_date date, p_repick boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.bulk_repair_unbound_dispatches(p_machine_id uuid, p_dispatch_date date, p_reason text, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.bulk_set_machine_inclusion(p_plan_date date, p_is_included boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.bulk_upsert_pod_inventory_from_log(p_lines jsonb, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.cancel_dispatch_line(p_dispatch_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.cancel_m2m_transfer(p_transfer_id uuid, p_reason text, p_convert_source_to_return boolean, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.cancel_po(p_po_number text, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.cancel_po_line(p_po_line_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.check_receipt_duplicate_expiry_dates(p_po_id text, p_lines jsonb, p_additions jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.check_receipt_shelf_life_deviation(p_writer text, p_receipt_date date, p_entered_expiry date, p_boonz_product_id uuid, p_context jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.check_refill_coverage(p_plan_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.check_remove_without_replace(p_plan_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.check_stale_wm_confirmations() TO anon;
GRANT EXECUTE ON FUNCTION public.check_wh_expiry_anomaly() TO anon;
GRANT EXECUTE ON FUNCTION public.cleanup_orphan_dispatching(p_dispatch_date date, p_machine_names text[]) TO anon;
GRANT EXECUTE ON FUNCTION public.close_abandoned_warehouse_audit(p_audit_date date, p_reason text, p_caller_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.close_inventory_session(p_session_id uuid, p_closed_by uuid, p_summary jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.close_return_backlog(p_before date, p_reason text, p_dry_run boolean, p_caller_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.confirm_and_build(p_plan_date date, p_machine_names text[], p_cars integer) TO anon;
GRANT EXECUTE ON FUNCTION public.confirm_disposition_redeploy(p_event_id uuid, p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.confirm_m2m_delivery(p_transfer_id uuid, p_source_actual_qty numeric, p_dest_actual_qty numeric, p_caller_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.confirm_machine_packed(p_machine_name text, p_dispatch_date date, p_packed_by uuid, p_reason text, p_final boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.confirm_packed_transferred(p_dispatch_id uuid, p_confirmed_by uuid, p_batch_breakdown jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.confirm_physical_receipt(p_po_line_id uuid, p_physical_qty numeric, p_received_by uuid, p_notes text) TO anon;
GRANT EXECUTE ON FUNCTION public.confirm_recommendation_intent(p_intent_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.confirm_stitched_plan(p_plan_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.confirm_warehouse_status_proposal(p_proposal_id uuid, p_note text) TO anon;
GRANT EXECUTE ON FUNCTION public.conserve_split_dispatch_quantity() TO anon;
GRANT EXECUTE ON FUNCTION public.convert_removes_to_m2m_transfer(p_dispatch_ids uuid[], p_dest_machine_id uuid, p_dest_shelf_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.convert_shelf(p_plan_date date, p_machine_id uuid, p_shelf_id uuid, p_old_pod_product_id uuid, p_new_pod_product_id uuid, p_new_qty integer, p_return_mode text, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.correct_expiry_v1(p_scope text, p_row_id uuid, p_new_expiry date, p_reason text, p_caller_id uuid, p_dry_run boolean, p_override boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.correct_packed_m2m_transfer(p_transfer_id uuid, p_lines jsonb, p_reason text, p_caller_id uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.create_reconcile_disposition_line(p_machine_id uuid, p_shelf_id uuid, p_boonz_product_id uuid, p_qty numeric, p_expiration_date date, p_reason text, p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.create_refill_plan(p_plan_date date, p_machine_ids uuid[]) TO anon;
GRANT EXECUTE ON FUNCTION public.cron13_build_or_alert_v3() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_align_pod_lots_to_weimi_nightly() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_conservation_monitor() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_daily_inventory_reconciliation() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_finding_auto_heal() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_migration_window_alert() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_pending_return_alert(p_days integer) TO anon;
GRANT EXECUTE ON FUNCTION public.cron_phantom_pod_alert() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_refill_draft_missing_alert() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_shelf_index_drift_alert() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_slot_binding_drift_alert() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_stale_state_escalator() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_unmatched_weimi_alert() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_wh_batch_no_expiry_alert() TO anon;
GRANT EXECUTE ON FUNCTION public.cron_wh_routing_gap_alert() TO anon;
GRANT EXECUTE ON FUNCTION public.current_app_role() TO anon;
GRANT EXECUTE ON FUNCTION public.decline_dispatch_return(p_dispatch_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.decline_swap_pair(p_plan_date date, p_machine_id uuid, p_shelf_id uuid, p_dispatch_ids uuid[], p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.defer_dispatch_lines(p_dispatch_ids uuid[], p_target_date date, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.detect_shelf_overfill_on_receive() TO anon;
GRANT EXECUTE ON FUNCTION public.dispose_warehouse_return(p_wh_inventory_id uuid, p_disposition text, p_reason text, p_actor uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.drain_consumer_stock_phantom(p_wh_inventory_id uuid, p_reason text, p_drained_by uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.drain_phantom_consumer_stock(p_wh_inventory_id uuid, p_units numeric, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.drain_phantom_consumer_stock_batch_run(p_caller_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.driver_add_flagged_row(p_machine_id uuid, p_shelf_code text, p_boonz_product_id uuid, p_quantity numeric, p_action text, p_dispatch_date date, p_source_kind text, p_source_warehouse_id uuid, p_source_machine_id uuid, p_edit_role text, p_reason text, p_conductor_session text) TO anon;
GRANT EXECUTE ON FUNCTION public.driver_confirm_remove(p_dispatch_id uuid, p_qty_removed numeric, p_batch_breakdown jsonb, p_driver_id uuid, p_notes text) TO anon;
GRANT EXECUTE ON FUNCTION public.driver_propose_adjustment(p_machine_id uuid, p_kind text, p_note text, p_boonz_product_id uuid, p_shelf_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.driver_report_dispatch_outcome(p_dispatch_id uuid, p_outcome text, p_actual_qty integer) TO anon;
GRANT EXECUTE ON FUNCTION public.edit_dispatch_product(p_dispatch_id uuid, p_new_boonz_product_id uuid, p_edit_role text, p_reason text, p_conductor_session text) TO anon;
GRANT EXECUTE ON FUNCTION public.edit_dispatch_qty(p_dispatch_id uuid, p_new_qty numeric, p_edit_role text, p_reason text, p_conductor_session text) TO anon;
GRANT EXECUTE ON FUNCTION public.edit_dispatch_shelf(p_dispatch_id uuid, p_new_shelf_code text, p_edit_role text, p_reason text, p_conductor_session text) TO anon;
GRANT EXECUTE ON FUNCTION public.edit_pod_refill_row(p_plan_date date, p_machine_id uuid, p_shelf_id uuid, p_pod_product_id uuid, p_action text, p_new_qty integer, p_reason text, p_conductor_session text) TO anon;
GRANT EXECUTE ON FUNCTION public.edit_purchase_order_line(p_po_line_id uuid, p_new_ordered_qty numeric, p_new_price_per_unit_aed numeric, p_new_expiry_date date, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.edit_transfer_qty(p_dispatch_id uuid, p_new_qty numeric, p_edit_role text, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.engine_add_pod(p_plan_date date, p_days_cover integer) TO anon;
GRANT EXECUTE ON FUNCTION public.engine_finalize_pod(p_plan_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.engine_finalize_pod(p_plan_date date, p_machine_ids uuid[]) TO anon;
GRANT EXECUTE ON FUNCTION public.engine_swap_pod(p_plan_date date, p_max_swaps_per_machine integer, p_min_pearson numeric, p_days_cover integer) TO anon;
GRANT EXECUTE ON FUNCTION public.ensure_vox_placeholder(p_boonz_product_id uuid, p_warehouse_id uuid, p_caller uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.eod_auto_release_unpicked() TO anon;
GRANT EXECUTE ON FUNCTION public.expire_intents() TO anon;
GRANT EXECUTE ON FUNCTION public.flag_intent_threats() TO anon;
GRANT EXECUTE ON FUNCTION public.flag_multivariant_pack_without_variant_confirmation() TO anon;
GRANT EXECUTE ON FUNCTION public.flag_multivariant_return_without_correction() TO anon;
GRANT EXECUTE ON FUNCTION public.flag_remove_with_transfer_intent() TO anon;
GRANT EXECUTE ON FUNCTION public.force_release_refill_plan_lock(p_plan_date date, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_candidate_affinity(p_machine_id uuid, p_cand_pod_product_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_daily_sales_summary(p_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.get_dashboard_ops() TO anon;
GRANT EXECUTE ON FUNCTION public.get_dashboard_ops_cached() TO anon;
GRANT EXECUTE ON FUNCTION public.get_dashboard_sales(p_include_vox boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.get_decom_wh_signals() TO anon;
GRANT EXECUTE ON FUNCTION public.get_ghost_pod_signals() TO anon;
GRANT EXECUTE ON FUNCTION public.get_machine_expiry_detail(p_machine_name text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_machine_health_cached() TO anon;
GRANT EXECUTE ON FUNCTION public.get_open_po_lines(p_supplier_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_operational_signals() TO anon;
GRANT EXECUTE ON FUNCTION public.get_payment_default_summary(p_date_from date, p_date_to date, p_venue_group text, p_machine_ids uuid[]) TO anon;
GRANT EXECUTE ON FUNCTION public.get_procurement_demand(p_lookback_days integer, p_buffer_pct numeric, p_source text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_procurement_demand_pod(p_lookback_days integer, p_source text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_product_performance(p_bucket text, p_as_of date) TO anon;
GRANT EXECUTE ON FUNCTION public.get_product_velocity_ledger(p_weeks integer, p_scope text, p_level text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_sales_by_machine(lookback_days integer) TO anon;
GRANT EXECUTE ON FUNCTION public.get_staging_errors(p_batch_label text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_stale_dispatch_signals() TO anon;
GRANT EXECUTE ON FUNCTION public.get_stale_visit_signals() TO anon;
GRANT EXECUTE ON FUNCTION public.get_stock_overview() TO anon;
GRANT EXECUTE ON FUNCTION public.get_venue_terms(p_venue_group text) TO anon;
GRANT EXECUTE ON FUNCTION public.get_vox_sites() TO anon;
GRANT EXECUTE ON FUNCTION public.guard_pod_inventory_write() TO anon;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO anon;
GRANT EXECUTE ON FUNCTION public.has_boonz_tracker_access() TO anon;
GRANT EXECUTE ON FUNCTION public.inactivate_warehouse_row(p_wh_inventory_id uuid, p_reason text, p_inactivated_by uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.ingest_alerts_into_ledger() TO anon;
GRANT EXECUTE ON FUNCTION public.inject_swap(p_plan_date date, p_machine_name text, p_shelf_code text, p_remove_pod_product text, p_add_pod_product text, p_add_boonz_product text, p_add_quantity integer, p_comment text) TO anon;
GRANT EXECUTE ON FUNCTION public.issue_soa_number(p_client_code text, p_scope_type text, p_scope_tag text, p_venue_group text, p_machine_ids uuid[], p_period_from date, p_period_to date, p_currency text, p_total_sales numeric, p_net_client_revenue numeric, p_notes text) TO anon;
GRANT EXECUTE ON FUNCTION public.load_dow_profile_v3(p_lookback_days integer) TO anon;
GRANT EXECUTE ON FUNCTION public.log_dispatch_expiry_drift() TO anon;
GRANT EXECUTE ON FUNCTION public.log_driver_task_procurement_event() TO anon;
GRANT EXECUTE ON FUNCTION public.log_expiry_entry_suspect(p_writer text, p_reference_date date, p_entered_expiry date, p_context jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.log_manual_refill(p_machine_name text, p_source_warehouse_id uuid, p_refill_date date, p_lines jsonb, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.log_retroactive_refill_visit(p_machine_id uuid, p_visit_date date, p_lines jsonb, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.log_wh_mutation(p_wh_inventory_id uuid, p_boonz_product_id uuid, p_adjusted_by uuid, p_old_qty numeric, p_new_qty numeric, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.mark_dispatch_vox_sourced(p_dispatch_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.mark_dispatched(p_dispatch_ids uuid[]) TO anon;
GRANT EXECUTE ON FUNCTION public.mark_internal_transfer(p_plan_date date, p_source_machine_name text, p_dest_machine_name text, p_pod_product_id uuid, p_qty integer) TO anon;
GRANT EXECUTE ON FUNCTION public.mark_picked_up(p_dispatch_ids uuid[]) TO anon;
GRANT EXECUTE ON FUNCTION public.monitor_stuck_remove_dispatches() TO anon;
GRANT EXECUTE ON FUNCTION public.monitor_weimi_slot_drift() TO anon;
GRANT EXECUTE ON FUNCTION public.override_refill_quantity(p_plan_date date, p_machine_name text, p_shelf_code text, p_new_quantity integer) TO anon;
GRANT EXECUTE ON FUNCTION public.pack_dispatch_line(p_dispatch_id uuid, p_picks jsonb, p_packed_by uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.pick_machine_manually(p_plan_date date, p_machine_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.pick_machines_for_refill(p_plan_date date, p_cars integer, p_per_car integer) TO anon;
GRANT EXECUTE ON FUNCTION public.pick_machines_v12(p_plan_date date, p_cap integer) TO anon;
GRANT EXECUTE ON FUNCTION public.process_adyen_staging(p_batch_label text, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.process_weimi_staging(p_batch_label text, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.propagate_expiry_correction(p_wh_inventory_id uuid, p_dry_run boolean, p_caller_id uuid, p_override boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.propose_batch_dissolution_plan(p_wh_inventory_id uuid, p_max_residual_units integer, p_safety_buffer_days integer, p_rationale text) TO anon;
GRANT EXECUTE ON FUNCTION public.propose_decommission_plan(p_pod_product_id uuid, p_target_completion_date date, p_max_residual_units integer, p_machine_scope uuid[], p_rationale text, p_min_pearson numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.propose_inactivate_on_zero_stock() TO anon;
GRANT EXECUTE ON FUNCTION public.propose_pod_inventory_add(p_machine_id uuid, p_shelf_id uuid, p_boonz_product_id uuid, p_quantity numeric, p_expiration_date date, p_notes text, p_photo_path text, p_correlation_id uuid, p_proposed_by uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.propose_pod_inventory_edit(p_machine_id uuid, p_shelf_code text, p_boonz_product_id uuid, p_edit_type text, p_qty numeric, p_reason text, p_caller_id uuid, p_correlation_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.propose_reactivate_on_stock_return() TO anon;
GRANT EXECUTE ON FUNCTION public.propose_rebalance_plan(p_pod_product_id uuid, p_min_donor_stock integer, p_min_donor_v_ratio numeric, p_rationale text) TO anon;
GRANT EXECUTE ON FUNCTION public.propose_recommendation_intent(p_machine_id uuid, p_shelf_id uuid, p_level text, p_boonz_product_id uuid, p_pod_product_id uuid, p_action text, p_magnitude numeric, p_source text, p_raw_text text, p_note text) TO anon;
GRANT EXECUTE ON FUNCTION public.propose_wh_redeploy(p_wh_inventory_id uuid, p_target_machine_id uuid, p_qty numeric, p_reason text, p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.purge_test_inventory(p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.purge_warehouse_ghosts(p_warehouse_id uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.reactivate_warehouse_row(p_wh_inventory_id uuid, p_new_warehouse_stock numeric, p_reason text, p_source_doc text, p_reactivated_by uuid, p_new_expiration_date date, p_new_wh_location text) TO anon;
GRANT EXECUTE ON FUNCTION public.rebind_slot_lifecycle_from_weimi(p_machine_ids uuid[], p_dry_run boolean, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.rebind_stale_dispatch_pins(p_machine_id uuid, p_dispatch_date date, p_actor uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.rebuild_slot_profile_pool() TO anon;
GRANT EXECUTE ON FUNCTION public.receive_all_dispatches_for_machine(p_machine_id uuid, p_dispatch_date date, p_use_filled_as_received boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.receive_dispatch_line(p_dispatch_id uuid, p_filled_quantity numeric, p_received_by uuid, p_batch_breakdown jsonb, p_override boolean, p_override_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.receive_po_addition_into_machine(p_addition_id uuid, p_machine_id uuid, p_shelf_code text, p_visit_date date, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.reconcile_delivered_consumer_stock(p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.reconcile_pod_inventory_shelf(p_machine_id uuid, p_shelf_id uuid, p_new_pod_product_id uuid, p_reason text, p_confirm boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.reconcile_shelf_identity_weimi(p_machine_id uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.record_actual_refill(p_machine_name text, p_plan_date date, p_lines jsonb, p_source text, p_actor uuid, p_reason text, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.record_cash_recovery(p_merchant_reference text, p_recovered_amount numeric, p_reason text, p_collected_by text, p_tender_method text, p_recovered_at timestamp with time zone, p_notes text) TO anon;
GRANT EXECUTE ON FUNCTION public.record_remove_leg_outcome(p_dispatch_id uuid, p_driver_outcome text, p_driver_outcome_qty integer, p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.record_variant_correction(p_refill_dispatching_id uuid, p_planned_variant_id uuid, p_new_variant_id uuid, p_qty numeric, p_action_type text, p_reason_code text, p_free_text text) TO anon;
GRANT EXECUTE ON FUNCTION public.refresh_app_cache() TO anon;
GRANT EXECUTE ON FUNCTION public.refresh_correlation_pod(p_window_days integer, p_min_n_days integer, p_min_sales_per_side integer) TO anon;
GRANT EXECUTE ON FUNCTION public.refresh_product_scores() TO anon;
GRANT EXECUTE ON FUNCTION public.refresh_refill_draft(p_plan_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.refresh_sales_aggregated() TO anon;
GRANT EXECUTE ON FUNCTION public.refresh_wh_provenance_mv() TO anon;
GRANT EXECUTE ON FUNCTION public.register_terminal_move(p_unique_terminal_id text, p_new_machine_id uuid, p_effective_from date, p_attributed_name text, p_attributed_venue_group text, p_notes text) TO anon;
GRANT EXECUTE ON FUNCTION public.reject_pod_inventory_add(p_edit_id uuid, p_decision_note text, p_approver_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.reject_pod_inventory_edit(p_edit_id uuid, p_decision_note text, p_approver_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.reject_pod_refill_rows(p_plan_date date, p_machine_names text[], p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.reject_recommendation_intent(p_intent_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.reject_return(p_wh_inventory_id uuid, p_approver_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.reject_strategic_machine_tag(p_tag_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.reject_warehouse_status_proposal(p_proposal_id uuid, p_note text) TO anon;
GRANT EXECUTE ON FUNCTION public.release_fefo_reservation(p_dispatch_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.release_refill_plan_lock(p_plan_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.release_stale_unpacked_dispatches(p_dry_run boolean, p_before date) TO anon;
GRANT EXECUTE ON FUNCTION public.release_stale_wh_pins() TO anon;
GRANT EXECUTE ON FUNCTION public.release_wh_quarantine(p_wh_inventory_id uuid, p_reason text, p_verified_by uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.remove_dispatch_row(p_dispatch_id uuid, p_edit_role text, p_reason text, p_conductor_session text) TO anon;
GRANT EXECUTE ON FUNCTION public.remove_pod_inventory_batch(p_machine_id uuid, p_lines jsonb, p_caller_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.rename_machine(p_machine_id uuid, p_new_official_name text, p_new_location_type text, p_reason text, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.reopen_stitched_rows(p_plan_date date, p_machine_ids uuid[], p_shelf_ids uuid[], p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.repack_machine(p_machine_name text, p_dispatch_date date, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.repair_orphan_internal_transfer(p_orphan_dispatch_id uuid, p_destination_machine_id uuid, p_reason text, p_destination_shelf_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.repair_remove_leg_shelf_lot(p_dispatch_id uuid, p_reason text, p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.repair_remove_leg_shelf_lot_bulk(p_plan_date date, p_machine_name text, p_reason text, p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.repair_unbound_dispatch(p_dispatch_id uuid, p_wh_inventory_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.repin_dispatch_batch(p_dispatch_id uuid, p_wh_inventory_id uuid, p_reason text, p_caller_id uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.repurpose_machine(p_old_machine_id uuid, p_new_official_name text, p_new_pod_location text, p_new_location_type text, p_new_building_id text, p_new_source_of_supply text, p_new_venue_group text) TO anon;
GRANT EXECUTE ON FUNCTION public.reschedule_refill_plan(p_from_date date, p_to_date date, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.reset_and_restitch(p_plan_date date, p_machine_ids uuid[], p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.reset_approved_undispatched(p_plan_date date, p_machine_ids uuid[], p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.resolve_driver_feedback(p_plan_date date, p_machine_id uuid, p_engine_name text) TO anon;
GRANT EXECUTE ON FUNCTION public.resolve_finding(p_finding_id uuid, p_resolution_note text) TO anon;
GRANT EXECUTE ON FUNCTION public.restitch_after_edits(p_plan_date date, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.restore_pod_refill_row(p_plan_date date, p_machine_id uuid, p_shelf_id uuid, p_pod_product_id uuid, p_action text) TO anon;
GRANT EXECUTE ON FUNCTION public.resync_pod_inventory_from_weimi(p_machine_id uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.retry_staging_errors(p_batch_label text) TO anon;
GRANT EXECUTE ON FUNCTION public.return_all_dispatches_for_machine(p_machine_id uuid, p_dispatch_date date, p_return_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.return_dispatch_line(p_dispatch_id uuid, p_return_reason text, p_returned_by uuid, p_batch_breakdown jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.reverse_cancel_dispatch_line(p_dispatch_id uuid, p_reason text, p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.review_driver_addition(p_dispatch_id uuid, p_decision text, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.revoke_intent_via_threat(p_threat_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.reweight_pod_splits(p_machine text, p_pod text, p_weights jsonb, p_reason text, p_rebuild boolean, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.run_pod_inventory_decrement() TO anon;
GRANT EXECUTE ON FUNCTION public.safe_monitoring_alert(p_source text, p_severity text, p_payload jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.seed_missing_slot_lifecycle(p_dry_run boolean, p_machine_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.seed_shelf_configurations(p_machine_name text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_demand_factor_v3(p_source text, p_iso_year integer, p_iso_week integer, p_dow smallint, p_valid_from date, p_valid_to date, p_machine_id uuid, p_machine_class text, p_factor numeric, p_note text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_dispatch_include(p_dispatch_id uuid, p_include boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.set_dispatch_line_breakdown(p_dispatch_id uuid, p_batch_breakdown jsonb, p_edit_role text, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_dispatch_source(p_dispatch_id uuid, p_source_kind text, p_source_warehouse_id uuid, p_source_machine_id uuid, p_edit_role text, p_reason text, p_conductor_session text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_machine_inclusion(p_plan_date date, p_machine_id uuid, p_is_included boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.set_machine_relaunched_at(p_machine_id uuid, p_relaunched_at timestamp with time zone, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_machine_status(p_machine_id uuid, p_status text, p_adyen_status text, p_adyen_inventory_in_store text, p_installation_date date, p_reason text, p_caller uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.set_machine_warehouse(p_machine_id uuid, p_primary_warehouse_id uuid, p_secondary_warehouse_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_machine_weimi_slot_guard_override(p_machine_id uuid, p_override text, p_reason text, p_caller uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.set_product_lifecycle_status(p_pod_product_id uuid, p_status text, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.set_product_mapping_splits(p_pod_product_id uuid, p_machine_id uuid, p_splits jsonb, p_reason text, p_caller_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.set_swaps_enabled(p_enabled boolean, p_machine_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.set_warehouse_inventory_provenance() TO anon;
GRANT EXECUTE ON FUNCTION public.set_wh_batch_expiry(p_wh_inventory_id uuid, p_expiration_date date, p_reason text, p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.set_wh_quarantine(p_wh_inventory_id uuid, p_reason text, p_caller_id uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.skip_dispatch_line(p_dispatch_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.snapshot_engine_recommendations(p_plan_date date, p_machine_ids uuid[]) TO anon;
GRANT EXECUTE ON FUNCTION public.snapshot_shelf_stock() TO anon;
GRANT EXECUTE ON FUNCTION public.start_inventory_session(p_scope_warehouse_id uuid, p_scope_product_ids uuid[], p_session_slug text, p_started_by uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.stop_pod_refill_row(p_plan_date date, p_machine_id uuid, p_shelf_id uuid, p_pod_product_id uuid, p_action text, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.submit_driver_feedback(p_plan_date date, p_machine_name text, p_items jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.substitute_dispatch_line(p_dispatch_id uuid, p_new_boonz_product_id uuid, p_filled_qty numeric, p_reason text, p_actor uuid, p_source_tag text, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.swap_between_machines(p_source_machine_id uuid, p_dest_machine_id uuid, p_transfers jsonb, p_plan_date date, p_comment text) TO anon;
GRANT EXECUTE ON FUNCTION public.swap_dispatch_shelf(p_plan_date date, p_machine_id uuid, p_shelf_id uuid, p_remove_boonz_id uuid, p_remove_qty numeric, p_add_boonz_id uuid, p_add_qty numeric, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.swap_pod_refill_row(p_plan_date date, p_machine_id uuid, p_shelf_id uuid, p_old_pod_product_id uuid, p_new_pod_product_id uuid, p_action text, p_reason text, p_conductor_session text) TO anon;
GRANT EXECUTE ON FUNCTION public.swap_shelf_pod(p_plan_date date, p_machine_id uuid, p_shelf_id uuid, p_new_pod_product_id uuid, p_reason text, p_new_qty integer) TO anon;
GRANT EXECUTE ON FUNCTION public.sweep_stale_delivered_lines(p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.sweep_warehouse_hygiene(p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.sync_dispatch_expiry_from_pinned_wh() TO anon;
GRANT EXECUTE ON FUNCTION public.tg_auto_pickup_after_first_pickup() TO anon;
GRANT EXECUTE ON FUNCTION public.tg_auto_pickup_on_machine_complete() TO anon;
GRANT EXECUTE ON FUNCTION public.tg_block_internal_move_credit() TO anon;
GRANT EXECUTE ON FUNCTION public.tg_capture_refill_edit_signal() TO anon;
GRANT EXECUTE ON FUNCTION public.tg_credit_dispatch_remainder_on_receive() TO anon;
GRANT EXECUTE ON FUNCTION public.tg_enforce_pack_via_rpc() TO anon;
GRANT EXECUTE ON FUNCTION public.tg_provision_shelf_lifecycle() TO anon;
GRANT EXECUTE ON FUNCTION public.tg_reassert_conservation_on_confirm() TO anon;
GRANT EXECUTE ON FUNCTION public.tg_rebind_slot_lifecycle_on_add_confirm() TO anon;
GRANT EXECUTE ON FUNCTION public.toggle_machine_refill(p_machine_name text, p_include boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.transfer_warehouse_stock(p_source_warehouse_id uuid, p_dest_warehouse_id uuid, p_lines jsonb, p_transfer_date date, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.trg_fire_dispatch_on_approval() TO anon;
GRANT EXECUTE ON FUNCTION public.trg_po_number_one_po_id_fn() TO anon;
GRANT EXECUTE ON FUNCTION public.unpick_machine_to_visit(p_plan_date date, p_machine_id uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.unskip_dispatch_line(p_dispatch_id uuid, p_actor uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.update_dispatch_comment(p_dispatch_id uuid, p_comment text) TO anon;
GRANT EXECUTE ON FUNCTION public.upsert_aisle_snapshot(items jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.upsert_daily_sales(p_items jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.upsert_pod_snapshot(payload jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.upsert_refill_stock_snapshot(p_machine_id uuid, p_slots jsonb, p_source text) TO anon;
GRANT EXECUTE ON FUNCTION public.upsert_sales_lines(items jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.user_profiles_role_guard() TO anon;
GRANT EXECUTE ON FUNCTION public.v_picker_shadow_diff(p_plan_date date) TO anon;
GRANT EXECUTE ON FUNCTION public.void_refill_plan(p_plan_date date, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.wait_for_request(p_request_id bigint, p_timeout_seconds integer) TO anon;
GRANT EXECUTE ON FUNCTION public.warehouse_damage_writeoff(p_wh_inventory_id uuid, p_qty numeric, p_source text, p_reason text, p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.warehouse_expire_writeoff(p_wh_inventory_id uuid, p_reason text, p_caller_id uuid, p_disposal_code text) TO anon;
GRANT EXECUTE ON FUNCTION public.wh_approve_remove_receipt(p_dispatch_id uuid, p_actual_qty numeric, p_batch_breakdown jsonb, p_approved_by uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.wh_approve_remove_receipt_multivariant(p_parent_dispatch_id uuid, p_variant_breakdown jsonb, p_approved_by uuid, p_reason text) TO anon;
GRANT EXECUTE ON FUNCTION public.wm_confirm_line(p_line_id uuid, p_qty numeric, p_expiry date, p_outcome text, p_target_machine_id uuid, p_disposal_code text, p_reason text, p_caller uuid, p_dry_run boolean, p_batch_breakdown jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.wm_confirm_line_split(p_line_id uuid, p_splits jsonb, p_reason text, p_caller uuid, p_dry_run boolean) TO anon;
GRANT EXECUTE ON FUNCTION public.write_dispatch_plan(p_run_id uuid, p_dispatch_date date, p_lines jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.write_refill_plan(p_plan_date date, p_lines jsonb) TO anon;
