SET LOCAL statement_timeout = '120s';

-- ============================================================================
-- PRD-110 leg 83 · UNIT 1b — S-128(b): THE ONE-LINE SILENT-FAILURE KILL
--
-- P4.2's consumer (20260801022432) reads protect_depth / min_facing /
-- always_stock. All three are FLOORS. never_stock is a CEILING - a different
-- branch that must force qty to 0 AND survive the P2.5 unconditional floor - and
-- LAW 1 says it is not built before the fixture that proves it.
--
-- ⛔ THE FAILURE MODE WHILE PARKED IS SILENT: CS can approve a never_stock pin
--    today, the verb mints it, v_planning_pins_active_v3 reports it ACTIVE, and
--    the engine plans the shelf anyway. This migration converts that silent wrong
--    answer into a loud refusal. Proof: fixture 56 seq 35/41/42/43/44/45, RED at
--    42/3 (seqs 35, 41, 44) against the verb as it stands before this file.
--
-- ⛔ GENERATED BY SUBSTITUTION over pg_get_functiondef(), never transcribed, with
--    every anchor asserting its own occurrence count and the generated source
--    re-checked against the properties the fixture itself tests.
-- ============================================================================

DO $mig$
DECLARE
  d      text;
  n      int;
  anchor CONSTANT text := '  -- ---- approve ----';
  guard  text;
BEGIN
  -- ⛔ Assert a SINGLE overload before reading one. A silent overload would mean
  --    editing an arbitrary definition and leaving the live one untouched.
  SELECT count(*) INTO n
    FROM pg_proc p JOIN pg_namespace ns ON ns.oid = p.pronamespace
   WHERE ns.nspname = 'public' AND p.proname = 'approve_feedback_proposal_v3';
  IF n <> 1 THEN
    RAISE EXCEPTION 'expected exactly 1 approve_feedback_proposal_v3, found %', n;
  END IF;

  SELECT pg_get_functiondef(p.oid) INTO d
    FROM pg_proc p JOIN pg_namespace ns ON ns.oid = p.pronamespace
   WHERE ns.nspname = 'public' AND p.proname = 'approve_feedback_proposal_v3';

  -- ---- pre-conditions: the definition is the one this edit was written against ----
  IF strpos(d, 'not yet consumed by the engine') <> 0 THEN
    RAISE EXCEPTION 'the guard is already present - refusing to double-apply';
  END IF;
  IF strpos(d, 'contradicts live pin') = 0 THEN
    RAISE EXCEPTION 'the contradiction guard is missing - this is not the definition this edit targets';
  END IF;

  n := (length(d) - length(replace(d, anchor, ''))) / length(anchor);
  IF n <> 1 THEN
    RAISE EXCEPTION 'approve-branch anchor matched % times, expected exactly 1', n;
  END IF;

  guard :=
     E'  -- ⛔ S-128 INTERIM GUARD - never_stock IS NOT YET CONSUMED BY THE ENGINE.\n'
  || E'  --    Every kind P4.2 reads is a FLOOR; never_stock is a CEILING and needs its own\n'
  || E'  --    branch (force qty to 0, name itself as the clamp, and survive the P2.5\n'
  || E'  --    unconditional floor that would otherwise re-raise the line). Until that ships,\n'
  || E'  --    minting the pin would let CS approve a rule the plan then ignores in SILENCE,\n'
  || E'  --    which is strictly worse than refusing to mint it at all.\n'
  || E'  --    ⛔ ORDER IS LOAD-BEARING: this precedes the contradiction guard below on\n'
  || E'  --    purpose. "Revoke the live always_stock first" is TRUE but MISLEADING here - it\n'
  || E'  --    invites CS to retire a standing rule to unblock an approval that would still\n'
  || E'  --    fail afterwards. Asserted against prosrc by fixture 56 seq 44.\n'
  || E'  --    ⛔ REJECTION IS DELIBERATELY STILL ALLOWED (this sits inside the approve\n'
  || E'  --    branch, after the reject branch returns): a proposal that can be neither\n'
  || E'  --    approved nor rejected would sit in CS''s queue forever. Fixture 56 seq 43.\n'
  || E'  --    ⭐ REMOVE THIS BLOCK in the same unit that ships the ceiling branch, and\n'
  || E'  --    re-state fixture 56 seq 35/41/42/44 there - they are its tripwires.\n'
  || E'  IF pr.pin_kind = ''never_stock'' THEN\n'
  || E'    RAISE EXCEPTION ''approve_feedback_proposal_v3: pin kind never_stock is not yet consumed by the engine (S-128), so approving it would create a rule the plan silently ignores; reject this proposal, or approve it once the ceiling branch ships'';\n'
  || E'  END IF;\n';

  d := replace(d, anchor, anchor || E'\n' || guard);

  -- ---- post-conditions on the GENERATED source, before it is executed ----
  IF strpos(d, 'not yet consumed by the engine') = 0 THEN
    RAISE EXCEPTION 'post-check: the guard did not land';
  END IF;
  IF NOT (strpos(d, 'not yet consumed by the engine') < strpos(d, 'contradicts live pin')) THEN
    RAISE EXCEPTION 'post-check: the guard does not precede the contradiction guard';
  END IF;
  -- the reject branch must still return BEFORE the guard is reached
  IF NOT (strpos(d, '''status'',''rejected''') < strpos(d, 'not yet consumed by the engine')) THEN
    RAISE EXCEPTION 'post-check: the guard is not inside the approve branch - rejection would be blocked too';
  END IF;

  -- ⛔ pg_get_functiondef() returns NO trailing semicolon.
  EXECUTE d || ';';
END
$mig$;
